name: My Workflow
on: [push]
concurrency: 
  group: ${{ github.workflow }}
  cancel-in-progress: true
jobs:
  myJob:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    # Add your other steps here
